name: New Tag Trigger

on:
    push:
        tags:
            - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
    Tests:
        uses: ./.github/workflows/Tests.yml
    
    Build:
        uses: ./.github/workflows/Build.yml
        needs: Tests
    
    Publish:
        uses: ./.github/workflows/Publish.yml
        needs: Build
        with:
            art_name: ${{ needs.Build.outputs.art_name }}
        secrets: inherit 