name: Publish

on:
  workflow_call:
    inputs:
        art_name:
            required: true
            type: string

permissions:
  contents: write
  id-token: write


jobs:
    Publish_to_Releases:
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.art_name }}
            
            - name: Create Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    ./dist/*.whl
                    ./dist/*.tar.gz
              
    
    Publish_to_PIPY:
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.art_name }}
            
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.8'

            - name: Publish package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.TWINE_PASSWORD }}
                verbose: true
            
